#!/bin/bash

sed "s/[' ']//g" <<< "$1"
input_file="$1"
duration=$(ffprobe -v error -show_entries format=duration -of default=noprint_wrappers=1:nokey=1 "$input_file")
one_sixth_duration=$(awk '{print $1/6}' <<< "$duration")

ffmpeg -i "$input_file" -c copy -ss 0 -t "$one_sixth_duration" "${input_file%.*}_part1.mp4" \
-c copy -ss "$one_sixth_duration" -t "$one_sixth_duration" "${input_file%.*}_part2.mp4" \
-c copy -ss $(awk '{print $1 * 2 / 6}' <<< "$duration") -t "$one_sixth_duration" "${input_file%.*}_part3.mp4" \
-c copy -ss $(awk '{print $1 * 3 / 6}' <<< "$duration") -t "$one_sixth_duration" "${input_file%.*}_part4.mp4" \
-c copy -ss $(awk '{print $1 * 4 / 6}' <<< "$duration") -t "$one_sixth_duration" "${input_file%.*}_part5.mp4" \
-c copy -ss $(awk '{print $1 * 5 / 6}' <<< "$duration") "${input_file%.*}_part6.mp4"
